# About [ex2.cpp](https://github.com/C0DER11101/CPPNotesAndPrograms/blob/master/ExceptionHandling/Exercises/ex2.cpp)

This file shows us that we can have nested try catch blocks!!!

Just look at the `test()` function!!!

---
